resources:
  repositories:
    - repository: GithubRepo
      type: github
      endpoint: github.com_juhi037
      name: juhi037/ADOTestRepoNew

    - repository: azurerepos
      type: git
      name: RepoWithSecret


trigger:
- main




steps:
- checkout: GithubRepo

some changes
