resources:
  repositories:
    - repository: GithubRepo
      type: github
      endpoint: github.com_juhi037
      name: juhi037/ADOTestRepoNew

    - repository: azurerepos
      type: git
      name: RepoWithSecrets


trigger:
- main


pool:
  vmImage: 'ubuntu-latest'


steps:
- checkout: GithubRepo